services: 
  petclinic: 
    build: 
      context: . 
      dockerfile: Dockerfile 
      target: final 
    ports: 
      - 8000:8000 
      - 9999:8080 
    environment: 
    - SERVER_PORT=8080 
    - MYSQL_URL=jdbc:mysql://mysqlserver/petclinic
    - SPRING_PROFILES_ACTIVE=mysql 
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=petclinic
    - MYSQL_PASSWORD=petclinic
    - MYSQL_DATABASE=petclinic
    volumes: 
      - ./:/app 
    depends_on: 
      - healthcheck 
  mysqlserver: 
    image: mysql/mysql-server:8.0
    ports: 
      - 3306:3306 
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes: 
      - mysql_data:/var/lib/mysql 
      - mysql_config:/etc/mysql/conf.d 
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 20s
#  test:
#    image: 
volumes: 
  mysql_data: 
  mysql_config:






